var informacion = {

    cendi: $('#cendi').val(),
    foto: fotoURL,
    folio: 55,
    grupo: $('#grupo').val(),

    //Datos niño
    primer_apellido: $('#primer_apellido').val(),
    segundo_apellido: $('#segundo_apellido').val(),
    nombre: $('#nombre').val(),
    fecha: $('#fecha').val(),
    edadAnios: $('#edadAnios').val(),
    edadMeses: $('#edadMeses').val(),
    email: $('#email').val(),
    curp: $('#curp').val(),

    //Datos de derechohabiente
    primer_apelido_derecho: $('#primer_apelido_derecho').val(),
    segundo_apellido_derecho: $('#segundo_apellido_derecho').val(),
    nombre_derecho: $('#nombre_derecho').val(),
    calle: $('#calle').val(),
    noExt: $('#noExt').val(),
    noInt: $('#noInt').val(),
    colonia: $('#colonia').val(),
    alcaldia: $('#alcaldia').val(),
    entidad: $('#entidad').val(),
    cp: $('#cp').val(),
    telefono_fijo: $('#telefono_fijo').val(),
    telefono_celular: $('#telefono_celular').val(),
    email_derecho: $('#email_derecho').val(),
    ocupacion: $('#ocupacion').val(),
    curp_derecho: $('#curp_derecho').val(),
    puesto: $('#puesto').val(),
    sueldo: $('#sueldo').val(),
    numero_empleado: $('#numero_empleado').val(),
    adscripcion: $('#adscripcion').val(),
    horario: $('#horario').val(),
    extension: $('#extension').val(),

    //Datos del conyuge
    tienec: $('#tienec').val(),
    primer_apelido_conyuge: $('#primer_apelido_conyuge').val(),
    segundo_apellido_conyuge: $('#segundo_apellido_conyuge').val(),
    nombre_conyuge: $('#nombre_conyuge').val(),
    calle_conyuge: $('#calle_conyuge').val(),
    noExt_conyuge: $('#noExt_conyuge').val(),
    noInt_conyuge: $('#noInt_conyuge').val(),
    colonia_conyuge: $('#colonia_conyuge').val(),
    alcaldia_conyuge: $('#alcaldia_conyuge').val(),
    entidad_conyuge: $('#entidad_conyuge').val(),
    cp_conyuge: $('#cp_conyuge').val(),
    telefono_fijo_conyuge: $('#telefono_fijo_conyuge').val(),
    telefono_celular_conyuge: $('#telefono_celular_conyuge').val(),
    lugar_trabajo_conyuge: $('#lugar_trabajo_conyuge').val(),
    domicilio_trabajo_conyuge: $('#domicilio_trabajo_conyuge').val(),
    telefono_trabajo_conyuge: $('#telefono_trabajo_conyuge').val(),
    extension_conyuge: $('#extension_conyuge').val()
};
