<?php

$resp = array(
    array(

        'cendi' => '#cendi',
        'foto' => 'https://www.ipn.mx/assets/files/saes/img/escudosNS/IPN-Default.png',
        'folio' => '12345',
        'grupo' => '#grupo',

        //Datos niño
        'primer_apellido' => '#primer_apellido',
        'segundo_apellido' => '#segundo_apellido',
        'nombre' => '#nombre',
        'fecha' => '#fecha',
        'edadAnios' => '#edadAnios',
        'edadMeses' => '#edadMeses',
        'email' => '#email',
        'curp' => '#curp',

        //Datos de derechohabiente
        'primer_apelido_derecho' => '#primer_apelido_derecho',
        'segundo_apellido_derecho' => '#segundo_apellido_derecho',
        'nombre_derecho' => '#nombre_derecho',
        'calle' => '#calle',
        'noExt' => '#noExt',
        'noInt' => '#noInt',
        'colonia' => '#colonia',
        'alcaldia' => '#alcaldia',
        'entidad' => '#entidad',
        'cp' => '#cp',
        'telefono_fijo' => '#telefono_fijo',
        'telefono_celular' => '#telefono_celular',
        'email_derecho' => '#email_derecho',
        'ocupacion' => '#ocupacion',
        'curp_derecho' => '#curp_derecho',
        'puesto' => '#puesto',
        'sueldo' => '#sueldo',
        'numero_empleado' => '#numero_empleado',
        'adscripcion' => '#adscripcion',
        'horario' => '#horario',
        'extension' => '#extension',

        //Datos del conyuge
        'tienec' => '#tienec',
        'primer_apelido_conyuge' => '#primer_apelido_conyuge',
        'segundo_apellido_conyuge' => '#segundo_apellido_conyuge',
        'nombre_conyuge' => '#nombre_conyuge',
        'calle_conyuge' => '#calle_conyuge',
        'noExt_conyuge' => '#noExt_conyuge',
        'noInt_conyuge' => '#noInt_conyuge',
        'colonia_conyuge' => '#colonia_conyuge',
        'alcaldia_conyuge' => '#alcaldia_conyuge',
        'entidad_conyuge' => '#entidad_conyuge',
        'cp_conyuge' => '#cp_conyuge',
        'telefono_fijo_conyuge' => '#telefono_fijo_conyuge',
        'telefono_celular_conyuge' => '#telefono_celular_conyuge',
        'lugar_trabajo_conyuge' => '#lugar_trabajo_conyuge',
        'domicilio_trabajo_conyuge' => '#domicilio_trabajo_conyuge',
        'telefono_trabajo_conyuge' => '#telefono_trabajo_conyuge',
        'extension_conyuge' => '#extension_conyuge'

    ),
    array(

        'cendi' => '#cendi',
        'foto' => 'https://www.ipn.mx/assets/files/saes/img/escudosNS/IPN-Default.png',
        'folio' => '3456',
        'grupo' => '#grupo',

        //Datos niño
        'primer_apellido' => '#primer_apellido',
        'segundo_apellido' => '#segundo_apellido',
        'nombre' => '#nombre',
        'fecha' => '#fecha',
        'edadAnios' => '#edadAnios',
        'edadMeses' => '#edadMeses',
        'email' => '#email',
        'curp' => '#curp',

        //Datos de derechohabiente
        'primer_apelido_derecho' => '#primer_apelido_derecho',
        'segundo_apellido_derecho' => '#segundo_apellido_derecho',
        'nombre_derecho' => '#nombre_derecho',
        'calle' => '#calle',
        'noExt' => '#noExt',
        'noInt' => '#noInt',
        'colonia' => '#colonia',
        'alcaldia' => '#alcaldia',
        'entidad' => '#entidad',
        'cp' => '#cp',
        'telefono_fijo' => '#telefono_fijo',
        'telefono_celular' => '#telefono_celular',
        'email_derecho' => '#email_derecho',
        'ocupacion' => '#ocupacion',
        'curp_derecho' => '#curp_derecho',
        'puesto' => '#puesto',
        'sueldo' => '#sueldo',
        'numero_empleado' => '#numero_empleado',
        'adscripcion' => '#adscripcion',
        'horario' => '#horario',
        'extension' => '#extension',

        //Datos del conyuge
        'tienec' => '#tienec',
        'primer_apelido_conyuge' => '#primer_apelido_conyuge',
        'segundo_apellido_conyuge' => '#segundo_apellido_conyuge',
        'nombre_conyuge' => '#nombre_conyuge',
        'calle_conyuge' => '#calle_conyuge',
        'noExt_conyuge' => '#noExt_conyuge',
        'noInt_conyuge' => '#noInt_conyuge',
        'colonia_conyuge' => '#colonia_conyuge',
        'alcaldia_conyuge' => '#alcaldia_conyuge',
        'entidad_conyuge' => '#entidad_conyuge',
        'cp_conyuge' => '#cp_conyuge',
        'telefono_fijo_conyuge' => '#telefono_fijo_conyuge',
        'telefono_celular_conyuge' => '#telefono_celular_conyuge',
        'lugar_trabajo_conyuge' => '#lugar_trabajo_conyuge',
        'domicilio_trabajo_conyuge' => '#domicilio_trabajo_conyuge',
        'telefono_trabajo_conyuge' => '#telefono_trabajo_conyuge',
        'extension_conyuge' => '#extension_conyuge'

    ),
    array(

        'cendi' => '#cendi',
        'foto' => 'https://www.ipn.mx/assets/files/saes/img/escudosNS/IPN-Default.png',
        'folio' => '6789',
        'grupo' => '#grupo',

        //Datos niño
        'primer_apellido' => '#primer_apellido',
        'segundo_apellido' => '#segundo_apellido',
        'nombre' => '#nombre',
        'fecha' => '#fecha',
        'edadAnios' => '#edadAnios',
        'edadMeses' => '#edadMeses',
        'email' => '#email',
        'curp' => '#curp',

        //Datos de derechohabiente
        'primer_apelido_derecho' => '#primer_apelido_derecho',
        'segundo_apellido_derecho' => '#segundo_apellido_derecho',
        'nombre_derecho' => '#nombre_derecho',
        'calle' => '#calle',
        'noExt' => '#noExt',
        'noInt' => '#noInt',
        'colonia' => '#colonia',
        'alcaldia' => '#alcaldia',
        'entidad' => '#entidad',
        'cp' => '#cp',
        'telefono_fijo' => '#telefono_fijo',
        'telefono_celular' => '#telefono_celular',
        'email_derecho' => '#email_derecho',
        'ocupacion' => '#ocupacion',
        'curp_derecho' => '#curp_derecho',
        'puesto' => '#puesto',
        'sueldo' => '#sueldo',
        'numero_empleado' => '#numero_empleado',
        'adscripcion' => '#adscripcion',
        'horario' => '#horario',
        'extension' => '#extension',

        //Datos del conyuge
        'tienec' => '#tienec',
        'primer_apelido_conyuge' => '#primer_apelido_conyuge',
        'segundo_apellido_conyuge' => '#segundo_apellido_conyuge',
        'nombre_conyuge' => '#nombre_conyuge',
        'calle_conyuge' => '#calle_conyuge',
        'noExt_conyuge' => '#noExt_conyuge',
        'noInt_conyuge' => '#noInt_conyuge',
        'colonia_conyuge' => '#colonia_conyuge',
        'alcaldia_conyuge' => '#alcaldia_conyuge',
        'entidad_conyuge' => '#entidad_conyuge',
        'cp_conyuge' => '#cp_conyuge',
        'telefono_fijo_conyuge' => '#telefono_fijo_conyuge',
        'telefono_celular_conyuge' => '#telefono_celular_conyuge',
        'lugar_trabajo_conyuge' => '#lugar_trabajo_conyuge',
        'domicilio_trabajo_conyuge' => '#domicilio_trabajo_conyuge',
        'telefono_trabajo_conyuge' => '#telefono_trabajo_conyuge',
        'extension_conyuge' => '#extension_conyuge'

    ),
    array(

        'cendi' => '#cendi',
        'foto' => 'https://www.ipn.mx/assets/files/saes/img/escudosNS/IPN-Default.png',
        'folio' => '9102',
        'grupo' => '#grupo',

        //Datos niño
        'primer_apellido' => '#primer_apellido',
        'segundo_apellido' => '#segundo_apellido',
        'nombre' => '#nombre',
        'fecha' => '#fecha',
        'edadAnios' => '#edadAnios',
        'edadMeses' => '#edadMeses',
        'email' => '#email',
        'curp' => '#curp',

        //Datos de derechohabiente
        'primer_apelido_derecho' => '#primer_apelido_derecho',
        'segundo_apellido_derecho' => '#segundo_apellido_derecho',
        'nombre_derecho' => '#nombre_derecho',
        'calle' => '#calle',
        'noExt' => '#noExt',
        'noInt' => '#noInt',
        'colonia' => '#colonia',
        'alcaldia' => '#alcaldia',
        'entidad' => '#entidad',
        'cp' => '#cp',
        'telefono_fijo' => '#telefono_fijo',
        'telefono_celular' => '#telefono_celular',
        'email_derecho' => '#email_derecho',
        'ocupacion' => '#ocupacion',
        'curp_derecho' => '#curp_derecho',
        'puesto' => '#puesto',
        'sueldo' => '#sueldo',
        'numero_empleado' => '#numero_empleado',
        'adscripcion' => '#adscripcion',
        'horario' => '#horario',
        'extension' => '#extension',

        //Datos del conyuge
        'tienec' => '#tienec',
        'primer_apelido_conyuge' => '#primer_apelido_conyuge',
        'segundo_apellido_conyuge' => '#segundo_apellido_conyuge',
        'nombre_conyuge' => '#nombre_conyuge',
        'calle_conyuge' => '#calle_conyuge',
        'noExt_conyuge' => '#noExt_conyuge',
        'noInt_conyuge' => '#noInt_conyuge',
        'colonia_conyuge' => '#colonia_conyuge',
        'alcaldia_conyuge' => '#alcaldia_conyuge',
        'entidad_conyuge' => '#entidad_conyuge',
        'cp_conyuge' => '#cp_conyuge',
        'telefono_fijo_conyuge' => '#telefono_fijo_conyuge',
        'telefono_celular_conyuge' => '#telefono_celular_conyuge',
        'lugar_trabajo_conyuge' => '#lugar_trabajo_conyuge',
        'domicilio_trabajo_conyuge' => '#domicilio_trabajo_conyuge',
        'telefono_trabajo_conyuge' => '#telefono_trabajo_conyuge',
        'extension_conyuge' => '#extension_conyuge'

    )
);

echo json_encode($resp);
?>